name: emotion-detection-api
services:
  - name: api
    dockerfile_path: Dockerfile
    source_dir: .
    github:
      branch: main
      deploy_on_push: true
      repo: Cherisea/Emotion-Aware-AI
    health_check:
      http_path: /health
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: GDRIVE_MODEL_URL
        scope: RUN_TIME
        type: SECRET
        value: ${GDRIVE_MODEL_URL} 