name: emotion-detection-api
region: nyc
services:
  - name: emotion-detection-api
    dockerfile_path: Dockerfile
    source_dir: .
    github:
      branch: main
      deploy_on_push: true
      repo: YOUR_GITHUB_USERNAME/Emotion-Aware-AI
    health_check:
      http_path: /docs
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: GDRIVE_MODEL_URL
        scope: RUN_TIME
        type: SECRET
        value: ${GDRIVE_MODEL_URL} 